### PR TITLE
Update what-is-the-default-directory-that-zap-uses.md

### PR DESCRIPTION
**Pull request by omerlh**
Update Zap path on Mac, at least according to what's running on my machine (Zap installed via brew)

### CODE REVIEW

**Comment by thc202** [comment]
That seems to be the installation directory, not the home directory.

**Comment by omerlh** [comment]
This one doesn't exist: `~/Library/Application Support/ZAP`, at least for me

**Comment by thc202** [comment]
Launch ZAP and check the paths in `Help` > `Support Info...`.

**Comment by omerlh** [comment]
Mine was on 
```
/Users/<user name>/Library/Application Support/ZAP/
```

**Comment by omerlh** [comment]
Ohh silly me - there is a space in the folder name! This is why it didn't worked 🤦

**Pull request closed without merging**
