### PR TITLE
[WIP] Prettified files using command npx prettier --write .

### PR DESCRIPTION
**Pull request by njmulsqb**
Hi,

I saw an issue https://github.com/zaproxy/zaproxy-website/issues/8 which mentioned the need of prettier on the code of zap website.

I have prettified whole website's code using prettier extension with the following command
```npx prettier --write .```

Reference: https://stackoverflow.com/questions/43666270/how-do-i-format-all-files-in-a-visual-studio-code-project

### CODE REVIEW

**Comment by thc202** [comment]
That issue is about changing the build to verify (and allow to apply) the format, not just for one-off.

**Comment by njmulsqb** [comment]
> That issue is about changing the build to verify (and allow to apply) the format, not just for one-off.

Sorry but the issue does not contains any detailed description, it just says "Prettify the code" which I did, nothing else mentioned.

**Comment by thc202** [comment]
Yes, sometimes the issues don't contain all required information.

**Comment by njmulsqb** [comment]
> Yes, sometimes the issues don't contain all required information.

Anyways, if you explain this issue to me in detail, I can work on it.

**Comment by thc202** [comment]
It's as mentioned in the previous comment, the build should verify and allow to apply the format.

**Pull request closed without merging**
