### PR TITLE
Changed automation framework documentation to reflect changes made in PR #4326 (closing Issue #7663)

### PR DESCRIPTION
**Pull request by DragosStefanNecula**
This PR:
https://github.com/zaproxy/zap-extensions/pull/4326/files

That was part of a effort to close this issue:
https://github.com/zaproxy/zaproxy/issues/7663

Resulted in the documentation being out of date.

This PR addresses that.

Thank you very much and I hope you have a nice day.

### CODE REVIEW

**Comment by kingthorin** [comment]
This is actually generated content. It should be updated I the zap-extensions repo (if it hasn't already).

**Comment by kingthorin** [comment]
Thanks for catching this and pointing it out.

It hasn't been updated: https://github.com/zaproxy/zap-extensions/blob/1c6031c6bda223bede4bee2d8bb49062f0dfcd4e/addOns/spiderAjax/src/main/javahelp/org/zaproxy/zap/extension/spiderAjax/resources/help/contents/automation.html#L28

**Comment by DragosStefanNecula** [comment]
Im going to work on that, wasn't aware, thank you for the pointer!

**Comment by DragosStefanNecula** [comment]
Hey, should I manually update these lines in all the files for the different languages, or are these generated?

**Comment by kingthorin** [comment]
Just the default (`help`). After that's updated it gets propagated to crowdin for translation and then fed back.

**Comment by DragosStefanNecula** [comment]
Moving to this PR, thank you so much for your help!

https://github.com/zaproxy/zap-extensions/pull/5883

**Comment by DragosStefanNecula** [comment]
@kingthorin hey, do you think I could do:

Dragos-Stefan Necula (dragosstefannecula.co.uk)

**Comment by kingthorin** [comment]
No problem

**Pull request closed without merging**
