### PR TITLE
Added new spider stats

### PR DESCRIPTION
**Pull request by psiinon**
Code changes: https://github.com/zaproxy/zaproxy/pull/6807

Note that the new ones have "since 2.11.0" is the descriptions - think
that a good way to indicate they are post 2.10.0?

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by kingthorin** [comment]
Maybe “as of” since 2.11 might be interpreted as >2.11

**Comment by psiinon** [comment]
Or "from" ?

**Comment by kingthorin** [comment]
Yup!

**Comment by psiinon** [comment]
Done :)

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Pull request merged**
