### PR TITLE
Blog JWT Support Addon

### PR DESCRIPTION
**Pull request by preetkaran20**
**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
Looks good.

Still needs to address Simon’s comment per the previous PR: More how-to on JWT fuzzing.

For future reference. You could have copied your new/changed content to a safe location, deleted your local branch. Re-created with the same branch name, reapplied your changes (backed up files). Then force pushed it back to origin, thus ending up in an up-to-date state with a good base and your changes in the original PR.

**Comment by preetkaran20** [comment]
> Looks good.
> 
> Still needs to address Simon’s comment per the previous PR: More how-to on JWT fuzzing.
> 
> For future reference. You could have copied your new/changed content to a safe location, deleted your local branch. Re-created with the same branch name, reapplied your changes (backed up files). Then force pushed it back to origin, thus ending up in an up-to-date state with a good base and your changes in the original PR.

sure. This DCO gives help if there is a failure and those commands cause all these issues.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Comment by preetkaran20** [comment]
@simon thanks for mentioning that point.

**Review by kingthorin — APPROVED** [review]
Thanks

**Pull request merged**
