### PR TITLE
Gap Between Buttons

### PR DESCRIPTION
**Pull request by Moeez905**
Hi there,
The "Quick start guide" and "Start now" buttons were too close in mobile view, 
I edited them in this push request, 
P.S Apologies for the error in the first commit

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks!
Looks like your code ay a bit out of date - hence the conflict.
And you will need to sign the DCO - see the [Details](https://github.com/zaproxy/zaproxy-website/pull/1743/checks?check_run_id=13169594613) for more info, but also please ask here if you have any more questions 😁

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/main/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by kingthorin** [comment]
Also it seems to need a rebase.

**Comment by Moeez905** [comment]
@psiinon @kingthorin I Got it Thanks! Working on it

**Comment by Moeez905** [comment]
Hi all,
I have tried using git remote add & gitch fetch upstream commands but the issue is still there!
kindly let me know which cmd will work for this.
thanks,

**Comment by njmulsqb** [comment]
Just a suggestion @Moeez905 in future try to work on a separate branch on your fork and avoid direct changes on master. 
I am not too good with git, maybe @kingthorin can help with the git issues as he has always been my savior in the past 2 years :)

**Comment by kingthorin** [comment]
I haven't checked this out and tested it at all. But is this really the correct way to correct the GAP between buttons? Did you try multiple screen sizes? Maybe a before and after screenshot would help here.

I looked quickly on my iPhone and don't see those two buttons on the screen, unless you meant "Download Now"? In which case they're side by side not stacked so if bottom margin actually helps in that case it seems more like a side effect than a true fix 🤷‍♂️

**Comment by kingthorin** [comment]
As for the conflict you should rebase your branch based on an up-to-date upstream/master and just trust the newer package-lock.json content.

Actually it might be easier/quicker to just do a hard reset based on an up-to-date upstream/master then re-implement your single line addition.

**Comment by njmulsqb** [comment]
@Moeez905 you can take guidance from this reply https://github.com/zaproxy/zap-extensions/pull/3134#issuecomment-916012628

**Comment by Moeez905** [comment]
> 

@kingthorin Yes I have checked that fix on various dimensions/devices via mozilla developers and its working fine on all,
(before-After attached - iphone 12/13).
And yes! on wide screens like Samsung note (screenshot attached) and in some models of iphones, it appears side-by-side, not stacked but button gap is still fine.
Adding margin is the simplest and I guess the only required thing to make it work as you can see, still if there's something I'm missing or against code-standards, It'd be great if you can share!
iphone AFTER
galaxy note
iphone BEFORE
 
Thanks,

**Comment by Moeez905** [comment]
I don't know how while playing and understanding git cmd's, it got closed 😅
can you please reopen it @kingthorin 😜

**Pull request closed without merging**
