### PR TITLE
Update data

### PR DESCRIPTION
**Pull request by thc202**
From:
zaproxy/zap-admin@8aee45d5f8cd5b31cd8c8e3832c1543c1c481a49

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by kingthorin — COMMENTED** [review]
API?

**Comment by thc202** [comment]
That's because it was not added to the TOC.

**Comment by psiinon** [comment]
That will require a code change :/ merge this and make that? We can also link the policies back to the relevant help..

**Comment by thc202** [comment]
Now with the API page, this is using unreleased content: zaproxy/zap-extensions#5954.

**Review by psiinon — APPROVED** [review]

**Comment by psiinon** [comment]
@kingthorin ok now?

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Absolutely!

**Pull request merged**
