### PR TITLE
Updated Crawl Maze Results

### PR DESCRIPTION
**Pull request by zapbot**
Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Comment by thc202** [comment]
Regressions in core and AJAX Spider.

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
Not sure worth merging as is.

**Comment by psiinon** [comment]
Arg. My bad - think I need to include the http url in the plan...

**Comment by thc202** [comment]
Thought it was being flaky.

**Pull request closed without merging**
