### PR TITLE
history: updates

### PR DESCRIPTION
**Pull request by kingthorin**
Sourced from GitHub, wiki.owasp.org, ZAP's help content, and zaproxy.org.

There's still lots more to add but this seemed like a good start.

### CODE REVIEW

**Comment by psiinon** [comment]
This seems to add a lot of noise which isnt really helpful. Or am I missing something?

**Comment by psiinon** [comment]
<details><summary>Screenshot</summary>
<p>

image

</p>
</details>

**Comment by kingthorin** [comment]
🤷‍♂️ depends how complete we want it to be I guess. I do plan to link the releases to the help entries I just hadn't gotten that far.

I guess ultimately we could have an event type set of checkboxes or something. So that people can control what they're seeing.

- [ ] Releases
- [ ] Events
- [ ] News
- [ ] People

Something like that..... 🤔

**Comment by psiinon** [comment]
I dont feel the need to spend too much time on this right now. But I dont think this PR really helps as it stands. People can just go to the blog for a lot of these details, I'd rather this section gave more of a 'story' type of background..

**Pull request closed without merging**
