### PR TITLE
Update alert pages

### PR DESCRIPTION
**Pull request by zapbot**
Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Should I rerun this to pickup the 9th CSP alert?

**Comment by thc202** [comment]
Sounds good.

**Comment by kingthorin** [comment]
Okay, I thought the workflow was this repo but I don't see it? Nor in mgmt or ext...

**Comment by kingthorin** [comment]
Found it...admin 😉

**Comment by kingthorin** [comment]
It wasn't picked up? Should the loops be using `<=`?

https://github.com/zaproxy/zap-admin/blob/81494614724a28572da08255badcfd84d57932c6/scripts/generate_alert_pages.js#L141

**Comment by thc202** [comment]
That uses the weekly and the (old) add-on bundled and the one released have the same version.

**Comment by thc202** [comment]
Actually live but similar problem (we can regenerate live not though).

**Comment by kingthorin** [comment]
Oh, no rush, it can wait till whatever schedule/trigger.

**Pull request merged**
