### PR TITLE
Add Mission Statement and Core Team info

### PR DESCRIPTION
**Pull request by psiinon**
Also added good second issues ;)

**This documents our principals and how we work together.
As such it should be approved by all of the core team before being merged :)**

Screenshot 2022-02-24 at 13-45-09 OWASP ZAP – Contributing Guide

Screenshot 2022-02-24 at 13-45-19 OWASP ZAP – Contribute Core Team

Screenshot 2022-02-24 at 13-45-52 OWASP ZAP – Community

Screenshot 2022-02-24 at 13-46-01 OWASP ZAP – Mission Statement

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Bread crumb on mission statement?

**Comment by psiinon** [comment]
Hum, I might have to move the page :/ 
+1 for an image but I dont have anything right now.
Ok to address those later?

**Comment by kingthorin** [comment]
Sure.

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
There was pending approval from @ricekot

**Comment by kingthorin** [comment]
Oh crud, sorry.

**Comment by ricekot** [comment]
No worries, it's all good, there was one change which I mentioned on IRC :).

**Pull request merged**
