### PR TITLE
Tweak links to use new linktext attribute

### PR DESCRIPTION
**Pull request by psiinon**
Required to support https://github.com/zaproxy/zap-extensions/pull/3089

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Seems fine,

**Comment by psiinon** [comment]
Will change to use a new linkLabel element, but only once the data is present :)

**Comment by psiinon** [comment]
Updated to use linktext but still WIP as the data hasnt been changed to add this yet.

**Comment by psiinon** [comment]
Also updated to update deprecated alert pages.
All planned changes done...

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Pull request merged**
