### PR TITLE
Switch to Libera Chat

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Could you tweak the redirect as well?

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy-website/blob/master/site/content/redirects/irc.md

**Comment by psiinon** [comment]
Good spot!

**Comment by psiinon** [comment]
Done

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
