### PR TITLE
NPM audit fix

### PR DESCRIPTION
**Pull request by psiinon**
The action which should do this is currently failing - https://github.com/zaproxy/zaproxy-website/runs/2210483223?check_suite_focus=true
```
fixed 0 of 9 vulnerabilities in 1489 scanned packages
  3 vulnerabilities required manual review and could not be updated
  3 package updates for 6 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
```
This is the result of running `npm audit fix --force` locally.
The site still build and seems to work ok :)

This doesnt fix everything but its a start:
```
npm audit fix                        
npm WARN mini-css-extract-plugin@0.9.0 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
npm WARN optimize-css-assets-webpack-plugin@5.0.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of webpack@^4.36.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@3.3.10 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 3.6s

45 packages are looking for funding
  run `npm fund` for details

fixed 0 of 3 vulnerabilities in 1406 scanned packages
  3 vulnerabilities required manual review and could not be updated
```

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Can reproduce the build problem here.

**Comment by psiinon** [comment]
But dont really know what the problem is :/
@rezen - any suggestions?

**Comment by rezen** [comment]
@psiinon reading the logs, looks like a webpack plugin (`copy-webpack-plugin`) has changed it's configuration signature. I'm guessing the constructor doesn't want an array anymore, but rather just the object. https://github.com/zaproxy/zaproxy-website/blob/master/webpack.common.js#L51

**Comment by psiinon** [comment]
@rezen - thanks - I tried that (removing the []) but now it fails with:
```
> zaproxy-website@1.0.0 build:webpack /app
> cross-env NODE_ENV=production webpack --config webpack.prod.js --hot --inline

Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, filter?, transformAll?, toType?, force?, priority?, info?, transform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/app/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new CopyPlugin (/app/node_modules/copy-webpack-plugin/dist/index.js:38:31)
    at Object.<anonymous> (/app/webpack.common.js:51:5)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/app/webpack.prod.js:6:16)
    at Module._compile (/app/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zaproxy-website@1.0.0 build:webpack: `cross-env NODE_ENV=production webpack --config webpack.prod.js --hot --inline`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zaproxy-website@1.0.0 build:webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-31T15_41_01_311Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zaproxy-website@1.0.0 build: `npm run build:webpack && npm run build:hugo`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zaproxy-website@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-31T15_41_01_322Z-debug.log
```

**Comment by rezen** [comment]
Okay, I got something to work, but not sure how to bring those changes into this PR? I made a PR against your fork's branch, but really am not sure what I'm doing 🤔

**Comment by psiinon** [comment]
@rezen I just took the easy route of raising a new PR from your branch: #393
Closing this PR in favour of that one.

**Pull request closed without merging**
