### PR TITLE
Blog changes

### PR DESCRIPTION
**Pull request by rezen**
It's not perfect, but it's an improvement! It pulls images out of the blog (not sure about the sorting) and uses the first(ish?) image and uses it for a preview of the blog post.

### CODE REVIEW

**Comment by rezen** [comment]
Screen Shot 2020-11-02 at 4 59 48 PM

**Comment by rezen** [comment]
Screen Shot 2020-11-02 at 5 02 49 PM

**Comment by kingthorin** [comment]
Nice work!

**Review by psiinon — APPROVED** [review]
Love it!

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
