### PR TITLE
All the npm updates!

### PR DESCRIPTION
**Pull request by rezen**
Doing preview and build everything appeared sane?

### CODE REVIEW

**Comment by rezen** [comment]
I can can't get over how much time it takes to keep npm updated :sweat_smile:

**Comment by kingthorin** [comment]
Geez no wonder I couldn't easily get this sorted out locally 😀

**Review by kingthorin — APPROVED** [review]
Seems good to me. The only thing that stands out is the terminal.css change, I assume it's just that modern browsers have better/proper support for that now?

**Comment by rezen** [comment]
With terminal.css there were 2 parts at play. You are correct in asserting better browser support for gradients, but also it seems the css gradient specification has changed since that css was written? One of the webpack plugins was complaining about the gradient spec being out of date.

**Comment by rezen** [comment]
Where does the screenshot end up?

**Comment by kingthorin** [comment]
Goto "Actions", then select the run you care about, you should see an "Artifacts" section toward the bottom.

https://github.com/zaproxy/zaproxy-website/actions/runs/1478290014
image

**Comment by kingthorin** [comment]
Is there anything special I need to do to get this working locally?

**Comment by kingthorin** [comment]
Got it going with docker, I must have messed up my node install on this kali image.

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]
Many thanks!

**Comment by thc202** [comment]
This affected the TOC of the User Guide, it's no longer showing the releases (not a big issue as they are shown in the main Releases page).

**Comment by thc202** [comment]
Seems the script file is now being changed each time? e.g.:
```diff
-".hot-update.json",c.h=()=>"baf0c8498428374304e9"
+".hot-update.json",c.h=()=>"f5e3f9d8059c37a23f9c"
```

**Comment by rezen** [comment]
@thc202 what is the url for the User Guide? https://www.zaproxy.org/docs/desktop/ ?

**Comment by thc202** [comment]
Yes.

**Comment by thc202** [comment]
Re https://github.com/zaproxy/zaproxy-website/pull/649#issuecomment-976673378, happened again in zaproxy/zaproxy.github.io#491, needs a config change in webpack?

**Comment by rezen** [comment]
Mmm webpack. I'll take a look this weekend

**Comment by kingthorin** [comment]
Looks like we have two dependabot things left, I’ll email you some details.

**Comment by rezen** [comment]
@thc202 still working through why the `[hashid]` is changing, it makes no sense to me 😿

**Comment by kingthorin** [comment]
Is webpack embedding a date stamp when it generates things?

**Comment by kingthorin** [comment]
Shall we just drop the hash? I suppose it’s supposed to be a cache buster but if the file isn’t being changed (really) does it matter?

**Pull request merged**
