### PR TITLE
form-handler updates

### PR DESCRIPTION
**Pull request by kingthorin**
- form-handler > Add moved note like the old docs/desktop/ui/dialogs/options/connection/.
    - Remove the images no longer needed.

### CODE REVIEW

**Comment by thc202** [comment]
#1850  :)

**Comment by kingthorin** [comment]
Removed amf bit in favor of #1850

**Comment by kingthorin** [comment]
Have we done that elsewhere?

**Comment by thc202** [comment]
e.g. https://github.com/zaproxy/zaproxy-website/blob/2f7cf30f623cafde3c4903ece8a4e29912389d97/site/content/faq/where-does-zap-put-its-logs.md

**Comment by thc202** [comment]
But leave as is, not sure it will be properly handled by the ToC.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
