### PR TITLE
Make search and tags work

### PR DESCRIPTION
**Pull request by cudandres**
- Making search work with highlighting
- Make tags work

### CODE REVIEW

**Comment by cudandres** [comment]
Screen Shot 2020-11-03 at 4 03 43 PM
Screen Shot 2020-11-03 at 4 03 30 PM

**Comment by rezen** [comment]
Yay for paying attention to my session 🤦

**Comment by kingthorin** [comment]
This is great, below tags do you think you could add "Authors" (ala https://github.com/zaproxy/zaproxy-website/issues/219)? [I'll understand if that's better left for another PR, I'm just bringing it up because it seems similar.]

Is the tags list top 10, or do we simply happen to have only 10 tags in use right now?

**Comment by rezen** [comment]
There is no limit being set with `{{range $name, $taxonomy := .Site.Taxonomies.tags}}` so I think there is only 10 tags.

Regarding authors there is not a clear path, I think that will take some research.

**Comment by kingthorin** [comment]
Thanks @rezen!

**Comment by psiinon** [comment]
Looks great!
I have wanted to enable / expose search and the tags for a long time :)
Only one comment - search applies to the whole site (well, not the API) rather than just the blog. Only showing it on the blog page is therefore a bit confusing.
We could just expose another search page and maybe include a comment on the blog search to make that clearer?
Other suggestions also appreciated :)

**Comment by rezen** [comment]
@psiinon good point, search does indeed include everything, but showing in that context only suggests otherwise. Search currently already exists (https://www.zaproxy.org/search/?q=api) but is not explicitly linked to. Do you have the original designs we can reference, I'm curious if search was included in them.

**Comment by rezen** [comment]
Maybe search should just be a widget at the bottom of every page?

**Comment by psiinon** [comment]
Yeah, I was trying to think of how that would look, but none of my ideas seemed to look any good. Hopefully you'll be better at that than me :D

**Comment by rezen** [comment]
image
<br />
image

**Comment by rezen** [comment]
I think maybe having search visible every page like seen above would work.

**Comment by rezen** [comment]
Maybe on the homepage too?

image

**Comment by psiinon** [comment]
The search bar looks a bit intrusive to me :/
The only other sites I've seen with that are search engines like Google, not sites relating to a project/product.
I was thinking it would be in the header/footer, possibly just as an icon.

**Comment by thc202** [comment]
> Do you have the original designs we can reference, I'm curious if search was included in them.

The search was in the top right corner before the download: 
design search location

**Comment by psiinon** [comment]
That looks good.
On a related note someones suggested that we could combine "Get Involved" and "Support" into a common "Community" menu item.
I'm mentioning this hear as adding the search box to the header would make it bigger, potentially causing problems with smaller screens, and combining the 2 menu items would then reduce it.
If we do want to add the search box to the header then we should check how it works on mobile - at the moment the menu items appear as a popup hamburger menu ...

**Comment by psiinon** [comment]
Raised an issue for the possible Community page: https://github.com/zaproxy/zaproxy-website/issues/242

**Comment by rezen** [comment]
Cool, I had a sense the search bar felt a bit intrusive as well, but when I reflected on what the primary reason some was on the site (looking for docs?) I thought maybe it would be more helpful than intrusive.

Thinking about space in the menu bar, I like the way https://webpack.js.org/ includes search in the menu where the icon is small and then expands. We wouldn't do a dropdown autosuggest, but do expanding bit when someone clicks on the icon?

**Comment by psiinon** [comment]
Oh yeah, I really like that. As long as it works ok on mobile too ;)

**Comment by rezen** [comment]
image
image
image

**Comment by rezen** [comment]
For desktop view, toggle search icon to expand search bar. For mobile the search bar is visible in the dropdown menu.

**Review by psiinon — APPROVED** [review]
Love it!

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thanks!

**Comment by rezen** [comment]
🥳  I'll be going back "underground" with the project I've been working on but these were some updates I had been wanting to make for quite awhile. I'm glad we could get those in!

**Comment by kingthorin** [comment]
Thanks @rezen!

**Comment by psiinon** [comment]
Yeah - many thanks @rezen - those were great changes!

**Pull request merged**
