### PR TITLE
Update FP/FN FAQ "report" links

### PR DESCRIPTION
**Pull request by kingthorin**
Tweak link for issue tracker

### CODE REVIEW

**Comment by psiinon** [comment]
Would also be nice to link to the relevant template from https://www.zaproxy.org/faq/how-do-i-report-a-false-negative/ :)

**Comment by kingthorin** [comment]
I figured the picker was best because then we couldn't have this same issue in the future.

**Comment by kingthorin** [comment]
Nudge

**Comment by thc202** [comment]
This PR is only changing the FP FAQ not FN (just saying as the later needs to be changed either way).

I'd be +1 to link to specific template, we don't change them often.

**Comment by kingthorin** [comment]
Okay, will try to tweak that before I head out 😉

**Comment by kingthorin** [comment]
Done & done

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by psiinon — APPROVED** [review]

**Pull request merged**
