### PR TITLE
Add Constants page

### PR DESCRIPTION
**Pull request by psiinon**
I've just put the Alert Confidences and Risks in for now, hence the WIP.

Screenshot 2022-07-25 at 13-05-08 OWASP ZAP – ZAP Constants

Does it look ok? Might we need descriptions?

What else should we add to start with?
I was thinking of:

- Alert source
- Request initiators

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
I've added the other types, along with the History refs.

Screenshot 2022-07-25 at 13-48-01 OWASP ZAP – ZAP Constants

OK like this or should I split the names into types and names?
And if so should the values be after the types and before the names?
eg

| Type | Value | Name | Code |
| --- | --- | --- | --- |
| Alert Confidence | 0 | False Positive | ... |
| Alert Confidence | 1 | Low | ... |
| Alert Confidence | 2 | Medium | ... |

**Comment by psiinon** [comment]
Updated:

Screenshot 2022-07-25 at 14-40-45 OWASP ZAP – ZAP Constants

Ready for review :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Review by ricekot — APPROVED** [review]
Thanks!

**Comment by kingthorin** [comment]
I’ve work!

Could we create some sort of custom Java annotation to script creation of this content?
(Assuming you agree it’s worth it.)

**Comment by psiinon** [comment]
I guess we could.
Would it be more or less effort that manually updating the yaml file? I dont know.
But if you fancy playing around with Java annotations then this could be a good use case to try them on :D

**Comment by kingthorin** [comment]
I'm probably over thinking it :shrug:

**Pull request merged**
