### PR TITLE
Remove ZAPCon header

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
I'll tackle the owasp.org changes this evening.

**Comment by ricekot** [comment]
The images used in the header could be removed as well.

**Comment by psiinon** [comment]
Good point, removed.

**Review by ricekot — APPROVED** [review]

**Review by kingthorin — APPROVED** [review]

**Comment by thc202** [comment]
There was an image that was being used by CSS, which was not removed.

**Comment by kingthorin** [comment]
I guess changes in https://github.com/zaproxy/zaproxy-website/blob/67dda1f8c15a8abcaf1a18f3289042f3d1c29812/src/css/_headers.scss also need to be reverted.

**Pull request merged**
