### PR TITLE
#244 Filtering for alerts

### PR DESCRIPTION
**Pull request by rezen**
image

### CODE REVIEW

**Comment by kingthorin** [comment]
Nice work! ❗ 

I didn't even know this was on the radar.

**Comment by psiinon** [comment]
Me neither - very cool!

**Review by psiinon — APPROVED** [review]
Works really well :)

**Comment by psiinon** [comment]
@rezen the build is failing due to the DCO check. Can you fix that? The instructions are in the 'Details' link...

**Comment by rezen** [comment]
Whenever I have a little margin I look at the Issues and see what I can quickly knockout 😄

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
