### PR TITLE
Update alert pages

### PR DESCRIPTION
**Pull request by zapbot**
Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Can we somehow make this more clear?

Plugin ID: 10094
[619](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:620)
  Failed on Content Cacheability getExampleAlerts
[620](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:621)
  Failed on Content Cacheability getRisk
[621](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:622)
  Failed on Content Cacheability getDescription,getDesc,getDescriptionMessage
[622](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:623)
  Failed on Content Cacheability getSolution,getSoln,getSolutionMessage
[623](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:624)
  Failed on Content Cacheability getReferences,getReference,getRefs,getReferenceMessage,getReferencesMessage
[624](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:625)
  Failed on Content Cacheability getCweId
[625](https://github.com/zaproxy/zap-admin/actions/runs/3201838738/jobs/5230205229#step:4:626)
  Failed on Content Cacheability getWascId


I get that some of the top level methods don’t exist but it’s unclear what the issue is with getExampleAlerts?
https://github.com/zaproxy/zap-extensions/pull/4097/files

Looking at this just now I see I didn’t set Uri on the third entry, is that it?

**Comment by thc202** [comment]
The alpha scan rules are installed from the marketplace so it's not using that code.

**Review by thc202 — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks for clarifying.

**Comment by kingthorin** [comment]
I'll PR a tweak shortly to make that consistent.

**Comment by thc202** [comment]
What's not consistent?

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zap-extensions/pull/4097/files#diff-5f892ac4f1ca2230b6e5860d74dbd75050635fe8c00ebf3d85ac459f7a032ee9R727-R735
The third one doesn't have URL set.

**Comment by thc202** [comment]
OK, the URL is not used for the docs, +1 for consistency anyway.

**Pull request merged**
