### PR TITLE
added gap between orange and blue btn

### PR DESCRIPTION
**Pull request by Moeez905**
fixes partially zaproxy/zaproxy-website#3

### CODE REVIEW

**Comment by psiinon** [comment]
Before:
Screenshot 2023-05-09 at 14-52-26 The ZAP Homepage

After:
Screenshot 2023-05-09 at 14-52-40 The ZAP Homepage

**Comment by thc202** [comment]
I'd have expected these changes to be applied conditionally to smaller screens (though in this specific case it does not matter).

**Comment by Moeez905** [comment]
Thank You @psiinon for considering my changes and apologies for petty mistakes but sure enough, it'll get better with time as this openSource project already taught me a lot and I'm continuously learning

**Comment by Moeez905** [comment]
> Looks much better to me!

Thanks, Is there anything left from my side or are we good to merge?

**Review by kingthorin — APPROVED** [review]

**Comment by njmulsqb** [comment]
Congratulations @Moeez905 on your first PR, well-done!

**Pull request merged**
