### PR TITLE
Fix typo in Automation Framework page

### PR DESCRIPTION
**Pull request by njmulsqb**
Spelling fix

**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by psiinon — APPROVED** [review]

**Comment by kingthorin** [comment]
I know you can’t signoff on this since you did it via the web UI. Could you just confirm that you agree to the DCO? https://developercertificate.org/

**Comment by njmulsqb** [comment]
> @njmulsqb to fix the failing DCO check see https://github.com/zaproxy/zaproxy-website/pull/799/checks?check_run_id=5358387669 :)

Yeah I made the changes via web git, is there anyway to sign the commit using web version?

**Comment by njmulsqb** [comment]
> I know you can’t signoff on this since you did it via the web UI. Could you just confirm that you agree to the DCO? https://developercertificate.org/

I have signed it by taking clone locally.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
