### PR TITLE
FAQ: Scan inconsistencies

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
What about things like docker vs desktop, updates vs not, re-scanning something you’ve already scanned, etc

**Comment by psiinon** [comment]
Good points! And differing add-ons / rules installed / enabled ...
I'll update it for those things...

**Review by kingthorin — APPROVED** [review]
Thanks

**Review by thc202 — APPROVED** [review]

**Pull request merged**
