### PR TITLE
Docs: Automate ZAP

### PR DESCRIPTION
**Pull request by psiinon**
Provides a landing page for ZAP automation and a summary of the new Automation Framework.
Ready for review but not to be published until the add-ons have been released and the help pages updated.

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by ricekot — APPROVED** [review]
Looks good!

**Comment by kingthorin** [comment]
I think removing /docs/api is a mistake at this point, it’s linked all over the place. 

Maybe setup a redirect for it like we have for /irc or /slack?

**Comment by kingthorin** [comment]
Oh maybe that’s handled by the “link” attribute you set when you moved things?

**Comment by psiinon** [comment]
@kingthorin hang on, thats just because the API docs havnt been installed locally isnt it? I dont think my changes will have affected that...

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
I haven't tested locally I just saw that block removed and it made me concerned. We can always merge this and then apply a redirect in a separate PR if we discover there is a miss.

**Comment by thc202** [comment]
That's the content of the docs page (not changing actual links).

**Pull request merged**
