### PR TITLE
Document the macOS unverified developer workaround

### PR DESCRIPTION
**Pull request by christopherfrance**
**- Summary**

The app is not installable on MacOS without undocumented steps.

**- Test plan**

NA / documentation only. 

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

Document the MacOS unverified developer workaround.

Ref zaproxy/zaproxy#6162.

### CODE REVIEW

**Comment by kingthorin** [comment]
To address the DCO requirement you'll need to sign-off the commit(s):

- https://github.com/zaproxy/zaproxy/blob/develop/CONTRIBUTING.md#developer-certificate-of-origin
- https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by thc202** [comment]
This should be applied to the Getting Started Guide (which this page is based on).

**Comment by kingthorin** [comment]
@christopherfrance do you plan to finish this.

**Comment by kingthorin** [comment]
@christopherfrance do you plan to finish this?

**Comment by kingthorin** [comment]
@christopherfrance do you plan to finish this?

**Comment by kingthorin** [comment]
@christopherfrance do you plan to finish this?

**Comment by kingthorin** [comment]
This seems to have been abandon by the original contributor, will re-implement.

**Comment by christopherfrance** [comment]
Hi, sorry I missed the notifications for this issue. Thanks for updating the docs and for the great work on this project!

**Pull request closed without merging**
