### PR TITLE
Adding Script Console 

### PR DESCRIPTION
**Pull request by RADarkflow**
**- Summary**
Introducing Script Console within the documentation that highlights the ways to extend ZAP.

### CODE REVIEW

**Comment by thc202** [comment]
This blog post is specifically about changing ZAP source code.

**Comment by RADarkflow** [comment]
I believe its good to mention this as an extra info, especially for new beginners.

**Comment by RADarkflow** [comment]
> This blog post is specifically about changing ZAP source code.

I believe its good to mention this as an extra info or side note, especially for new beginners.

**Comment by psiinon** [comment]
The blog was written in 2014.
I'm all for updating the older blog posts to correct links but I dont think they should be substantially changed.
I'm all for new blog posts though :D

**Comment by RADarkflow** [comment]
> The blog was written in 2014. I'm all for updating the older blog posts to correct links but I dont think they should be substantially changed. I'm all for new blog posts though :D

old and gold :) from my humble exp with zap here, it would be nice to know about Script Console in this section for someone trying to hack into the code. I came to know abt Script Console by coincidence :)

**Comment by RADarkflow** [comment]
closed

**Pull request closed without merging**
