### PR TITLE
Fix: Issue 4 - Migrate ZAPping the Top 10

### PR DESCRIPTION
**Pull request by kingthorin**
- Add `guides` directory below `docs`.
- Within `guides` add ZAPping the Top 10 doc (migrated from OWASP wiki).
- `_index.md` within `guides` simply redirects users back up to `/docs/` if someone force browses there.

Fixes zaproxy/zaproxy-website#4

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by psiinon** [comment]
How about making this similar to the FAQs with sections like:

- Guides
  - Getting Started Guide - a good place to start if you are new to ZAP
  - Desktop User Guide - the help included with the ZAP desktop application
  - FAQ - Frequently Asked Questions
- Technical Details
  - API Details - a comprehensive guide to the ZAP API
  - JavaDocs (link to https://javadoc.io/doc/org.zaproxy/zap/latest/index.html)
- Automation (?)
  - Docker Images
  - Packages Scans

**Comment by psiinon** [comment]
Re ZAPping the Top 10 - how about haveing 3 columns, so the Ax's are in their own column and link to the relevant OWASP Top 10 pages? Hopefully thins will still work on mobile...

**Comment by psiinon** [comment]
Not sure which section things like ZAPping the Top 10 should go in yet :/ We could have some sort of bucket section... any thoughts?

**Comment by kingthorin** [comment]
I think ZAPping the Top 10 is a guide, and yes the idea of sections is good.

**Comment by kingthorin** [comment]
Further to: https://github.com/zaproxy/zaproxy-website/pull/14#issuecomment-581870142, and per discussions in IRC:
Category Heading > Links > Loop for categorized materials >> repeated for different categories

**Comment by cudandres** [comment]
Right now there are a couple guides (Getting Started Guide, Desktop User Guide) and "ZAPping the OWASP Top 10" feels like a guide. I think we should continue to build out the concept of guides as a type of content.

**Comment by kingthorin** [comment]
Hmmm that's an interesting idea. I think the other thing that was on people's radar was packaged scripts/scans which I think could also be framed the same way. @psiinon @thc202 is that good with you?

**Comment by psiinon** [comment]
Yeah, docker / packaged scan pages could be written as guides, so I like this idea.

**Comment by thc202** [comment]
Thanks!

**Comment by psiinon** [comment]
Hum, looks like the 'Common Components' header is for all of the right hand column - I would have expected it in the left column, and the associated text on the right hand side.

**Comment by kingthorin** [comment]
I'll have to look at it again. I think I misunderstood something you said earlier about the common components or maybe I broke something when I added the [Ax column](https://github.com/zaproxy/zaproxy-website/pull/14#issuecomment-581870142)

**Comment by kingthorin** [comment]
More like this?
image

**Comment by psiinon** [comment]
Exactly like that :)

**Comment by psiinon** [comment]
Could the 'Common Components' and A* titles be made a bit bigger as well? Not a biggie if thats too hard.

**Comment by kingthorin** [comment]
I think that's doable

**Comment by kingthorin** [comment]
I switched them from bold to H2 but had to run for the bus before I could preview it. Let me know if level 2 is too much.

**Comment by psiinon** [comment]
Or if it doesnt do the right thing at all ;~)
Screenshot_2020-02-24 OWASP ZAP – ZAPping the OWASP Top 10

**Comment by kingthorin** [comment]
Hmmm that’s interesting. Jekyll/Hugo could figure out markdown bold but not headings? Maybe inside tables I have to use HTML headings?

**Comment by thc202** [comment]
HTML is discouraged (i.e. stripped) in Markdown, probably better to use styles (or create a layout).

**Comment by kingthorin** [comment]
Added a shortcode for headings.

Note: Globally most of our headings are fairly large, then there's a big jump between 5 and 6 (6 almost seems like a caption). I've used 5 in the current implementation:

image

**Comment by thc202** [comment]
LGTM

**Pull request merged**
