### PR TITLE
Update Automate page

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
commited the suggestion 😁

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks. Squashed and merged.

**Comment by kingthorin** [comment]
Hrm, I was on my cell but I did change the drop down to squash and merge 😞

**Pull request merged**
