### PR TITLE
Updated Crawl Maze Results

### PR DESCRIPTION
**Pull request by zapbot**
Signed-off-by: zapbot <12745184+zapbot@users.noreply.github.com>

### CODE REVIEW

**Review by kingthorin — COMMENTED** [review]
I propose we change these to monthly. Since the targets aren't stable they're just kinda noise PRs

**Comment by thc202** [comment]
I'm fine with that.

**Comment by kingthorin** [comment]
Shouldn't we be merging these until fixed then?

**Comment by thc202** [comment]
The results are not always the same, sometimes it finds more and other times less.

**Comment by kingthorin** [comment]
Oh so it's kind of a performance/timing issue?

**Comment by psiinon** [comment]
AJAX Spider inconsistency, possibly due to the known concurrency bug.

**Comment by kingthorin** [comment]
Okay, thank you both.

**Pull request closed without merging**
