### PR TITLE
update missing risk,cwe and wasc.

### PR DESCRIPTION
**Pull request by pethers**
**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by kingthorin** [comment]
Thanks for doing this, however, the updates need to be done in the scan rules themselves in order to generate example alerts. 

The scan rules and some automation then generate this content.

**Comment by pethers** [comment]
Thanks for telling me, didn't know. Looked at the code links to find the details,  will this be updated anytime in the future ?

Need a complete list to add current rules to https://github.com/OtherDevOpsGene/zap-sonar-plugin/issues/64

**Comment by kingthorin** [comment]
Yes updated these details is a current work in progress.

**Comment by kingthorin** [comment]
You can check:
https://github.com/zaproxy/zaproxy/blob/develop/docs/scanners.md

It covers all the core rules and most third party.

**Pull request closed without merging**
