### PR TITLE
Update to node 23

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by psiinon** [comment]
Logo
**Checkmarx One – Scan Summary & Details** – [41931455\-ed6d\-4a2f\-b44f\-5207c87179df](https://eu.ast.checkmarx.net/projects/f9121e40-c915-4b13-bb15-36d946943fd8/scans?id=41931455-ed6d-4a2f-b44f-5207c87179df&branch=psiinon%2Fdocker%2Fnode23)
### New Issues
Severity|Issue|Source File / Package|Checkmarx Insight
---|---|---|---
HIGH|Missing User Instruction|/Dockerfile: [1](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L1)|A user should be specified in the dockerfile, otherwise the image will run as root
MEDIUM|Not Using JSON In CMD And ENTRYPOINT Arguments|/Dockerfile: [21](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L21)|Ensure that we are using JSON in the CMD and ENTRYPOINT Arguments
LOW|Healthcheck Instruction Missing|/Dockerfile: [1](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L1)|Ensure that HEALTHCHECK is being used. The HEALTHCHECK instruction tells Docker how to test a container to check that it is still working
### Fixed Issues
Severity|Issue|Source File / Package
---|---|---
HIGH|Missing User Instruction|/Dockerfile: [1](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L1)
MEDIUM|Not Using JSON In CMD And ENTRYPOINT Arguments|/Dockerfile: [21](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L21)
LOW|Healthcheck Instruction Missing|/Dockerfile: [1](https://github.com/psiinon/zaproxy-website/blob/docker/node23//Dockerfile#L1)
LOW|Unpinned Actions Full Length Commit SHA|/zap\-full\-scan\.yml: [17](https://github.com/psiinon/zaproxy-website/blob/docker/node23//.github/workflows/zap-full-scan.yml#L17)
LOW|Unpinned Actions Full Length Commit SHA|/zap\-scan\.yml: [17](https://github.com/psiinon/zaproxy-website/blob/docker/node23//.github/workflows/zap-scan.yml#L17)

**Comment by kingthorin** [comment]
Entry point/CMD thing can be fixed easily: https://docs.kics.io/2.1.2/queries/dockerfile-queries/b86987e1-6397-4619-81d5-8807f2387c79/

**Comment by kingthorin** [comment]
Adding a healthcheck should be easy too: https://docs.kics.io/1.7.1/queries/dockerfile-queries/b03a748a-542d-44f4-bb86-9199ab4fd2d5/

**Comment by psiinon** [comment]
OK, this is going to be harder than I thought...

**Pull request closed without merging**
