### PR TITLE
Add exim statistics

### PR DESCRIPTION
**Pull request by psiinon**
@kingthorin one for you to check :)

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by kingthorin — APPROVED** [review]
Looks good to me

Keep in mind exim hasn’t been released yet.

**Comment by psiinon** [comment]
In that case WIP until it is :) 
Any eta for that @kingthorin ?

**Comment by kingthorin** [comment]
https://github.com/zaproxy/zaproxy/issues/6579#issuecomment-996049581
:wink:

The first release couldn't be done soon I guess. Future releases could include the core stuff.

**Comment by kingthorin** [comment]
I guess this can go ahead now 😉

**Review by thc202 — APPROVED** [review]

**Pull request merged**
