### PR TITLE
Add alert details

### LINKED ISSUE #43: Have pages for scanner/alert/plugin types
For custom reports, it would be nice to able to link to a reference of all the scanner plugins' details. There could be a page that lists them all and then individual pages for each plugin. For each plugin we can create an entry and then have the templates generate a table with links to each individual plugin.

| id    | name       | cweid      | wascid | tags    | more |
|-------|------------|------------|--------|---------|------|
| 10020 | Xframe ... | 16         | 15     | headers |      |

```yaml
---
type: plugin
pluginid: 10020
name: Xframe....
----

Description down under here?
```

### PR DESCRIPTION
**Pull request by psiinon**
Fixes #43

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Added date info and deprecation info.

**Comment by kingthorin** [comment]
Somehow it needs to be clear that these are the primary details from the scan rules, and that some rules raise multiple alerts which aren't covered by this content. Or, so I think anyway 👍

Shall I add a function to the core cscan rule lasses like 'hasMultipleAlerts()' that defaults false but can be overridden by scan rules to facilitate this documentation, etc?

**Comment by psiinon** [comment]
Added: "Note that these are examples of the alerts raised - many rules include different details depending on the exact problem encountered."

**Comment by psiinon** [comment]
And removed the 5000? rules that are in the core and really infrastructure.

**Pull request merged**
