### PR TITLE
HoF Social Preview

### PR DESCRIPTION
**Pull request by kingthorin**
- Add generic trophy. (From unsplash https://unsplash.com/license)
- Add front matter.

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Comment by psiinon** [comment]
How about one of these 2 options for the image?
zapbot-trophy
zap-trophy

**Comment by kingthorin** [comment]
Talbot with the torch allows us to stick site themed.

**Comment by kingthorin** [comment]
@piinon can you email me the image or attach it somehow?

**Comment by psiinon** [comment]
Emailed :)

**Pull request merged**
