### PR TITLE
Add Basic Authors Pages

### PR DESCRIPTION
**Pull request by kingthorin**
Per: zaproxy/zaproxy-website#219

It's pretty default'ish, but it's something :grinning: Someone else can always attack it further in the future.

Click the control/triangle to the left to expand.

<details>
<summary>List View</summary>

image

</details>

<details>
<summary>Single View</summary>

image

</details>

Signed-off-by: kingthorin <kingthorin@users.noreply.github.com>

### CODE REVIEW

**Comment by psiinon** [comment]
I was actually thinking of creating core team pages - using the alert pages as a starting point, but those would be in addition to something like this :)

**Comment by kingthorin** [comment]
For record/reference the list.html addition is based largely on the tags one. I did have a look at the two pages via responsive design mode and they seemed okay on small screens.

**Comment by psiinon** [comment]
How can you get to the author pages? They dont seem to be linked from anywhere?
Possible options:

- a separate list of authors under the tags on the main blog page (my prefered option, I think)
- a "more from this author" or similar link under the authors name of each blog post
- an automatic link off each authors personal page (which dont yet exist, but I plan to add;)

Should the page be tweeked to be "Blog Authors" I was wondering if we should add authors to the videos as well.

Other than that looks fine to me - simple but functional :)

**Comment by kingthorin** [comment]
Excellent point, I'll see what I can do.

**Comment by kingthorin** [comment]
image

**Comment by kingthorin** [comment]
Ready for review

**Review by psiinon — APPROVED** [review]
Looks good to me. I can think of more things that could be done but this is a really good start :)

**Comment by kingthorin** [comment]
This was just meant to establish ‘something’ that’s why I didn’t put a close or fix keyword for the issue 😉

**Review by thc202 — APPROVED** [review]

**Pull request merged**
