### PR TITLE
FAQ: Why cant ZAP connect to my webapp

### PR DESCRIPTION
**Pull request by psiinon**
Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Review by ricekot — APPROVED** [review]

**Comment by kingthorin** [comment]
So there’s nothing wrong with this PR. But shouldn’t we suggest things to check like:
- DNS
  - Attempting access by IP instead of FQDN or hostname.
- Firewall(s)
- Http vs https

**Comment by thc202** [comment]
The usage of `curl` should help with that. (I don't mind seeing those items in the FAQ though.)

**Comment by psiinon** [comment]
I'll add something about trying the IP address. What do you think we should add for the others?

**Comment by psiinon** [comment]
Have dded: "Can you connect to it using the IP address rather than the FQDN or hostname?"

**Comment by kingthorin** [comment]
Just mention that they’re things to check. We don’t have to be specific with commands or whatever

**Comment by psiinon** [comment]
I'm still not really sure of the right phrasing to use ;)
"Try to find out if there are any firewalls installed which could be preventing access to your app"?

**Comment by kingthorin** [comment]
Ya something like that seems good

> Try to establish if there’s a Firewall preventing ZAP from accessing your target or network. (Keep in mind both host based software FWs and network devices.)

?

**Comment by psiinon** [comment]
Updated

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Thanks

**Pull request merged**
