### PR TITLE
add a meta description to the header of every page

### PR DESCRIPTION
**Pull request by lpmi-13**
**- Summary**

current site lacks meta description

This is an easy win for increasing SEO. Search crawlers love to see it.

**- Test plan**

Run a lighthouse audit to see the new and improved SEO score!

**- Description for the changelog**

Add meta tag for description in the header

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by kingthorin** [comment]
Does this need to be after the social preview part so that when used for linking/preview on twitter/FB/etc the specific content description is used before the generic one?

**Comment by lpmi-13** [comment]
The order shouldn't matter, since the opengraph and twitter previews use "og:description" and "twitter:description", respectively.

**Comment by kingthorin** [comment]
Okay

**Comment by kingthorin** [comment]
Another thought before I approve.

Do we want to set this in _config.yml or something, we use this tag line in a number of places, if it was a site variable it'd make future updates easier? (But maybe I'm over thinking it...)

**Comment by thc202** [comment]
For pages that already have a description it should use that instead of the generic description?

**Comment by lpmi-13** [comment]
ah yes, good points. Lemme keep digging into this "Hugo" thing all the kids are talking about, since this is literally my first time encountering it.

Out of curiosity, any particular reason we went with two completely different static site generators in two different languages for owasp.org and zaproxy.org?

**Comment by lpmi-13** [comment]
oh, and while I'm here, looks like the twitter preview isn't really coming through for the homepage anyway...so maybe I can do something about that (either here or in a separate PR)

no twitter preview

**Comment by kingthorin** [comment]
> either here or in a separate PR

Let us know what you prefer.

**Comment by lpmi-13** [comment]
alright, worked out the way that the conditional logic is expected in Hugo (basically just ended up copying the way that `twitter_cards.html` works) so that if the site already has a description, that one is preferred over the default defined in the `_config.yml`. Otherwise, the description defaults to the site-wide one set in the config.

Let's do the homepage twitter preview in a separate PR, just since I'm not sure how much time I've got to spend on it, and this part is ready to go now.

**Comment by thc202** [comment]
IMO we should not rely on the summary, that does not create good descriptions (e.g. https://github.com/zaproxy/zaproxy.github.io/compare/231f1127100286de675979827f4691e2f2b5be09..e72fb193163fb09d05b499a511afa915a4bdaf7f). The social preview is optional (#49) because of that.

**Comment by lpmi-13** [comment]
Summary has been removed. Lemme know if anything else should be updated.

**Pull request merged**
