### PR TITLE
New OWASP Top 10 social preview image

### PR DESCRIPTION
**Pull request by psiinon**
Old image

OWASP-Top-10

New image :)

ZAPping_TOP_10

Signed-off-by: Simon Bennetts <psiinon@gmail.com

### CODE REVIEW

**Comment by kingthorin** [comment]
Is the new image already present because this PR only contains the removal

**Comment by psiinon** [comment]
Weird, donno whats going on here :/

**Comment by psiinon** [comment]
No, I think it is there, its just smaller.
Do a view file: https://github.com/zaproxy/zaproxy-website/blob/f58403f38712ce0f079008272bb924bbaa7d94a6/site/static/img/docs/guides/OWASP-Top-10.png

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
Doh, yer right. Misleading UI.

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
