### PR TITLE
Tweak HoF link for GSoC 2019/2018 WebSockets Passive

### PR DESCRIPTION
**Pull request by kingthorin**
Switched URL to archive.org (Wayback Machine).
Per recent link check failures, ex: https://github.com/zaproxy/zaproxy-website/actions/runs/10650236424/job/29521359053

### CODE REVIEW

**Comment by thc202** [comment]
Maybe reinstate the same link in #2751?

**Comment by kingthorin** [comment]
If you mean the iOS apps one, sadly it wasn't indexed by archive.org

**Comment by thc202** [comment]
I meant the same link: https://github.com/zaproxy/zaproxy-website/pull/2751/files#diff-55f618c9f219a2f86aba7ad129c0e29ef403d7f329c3b1370798128ac4de9e37L132

**Comment by kingthorin** [comment]
Actually I found the 2018 blog on archive.org too, so I'll put that in.

**Comment by thc202** [comment]
That was not the link that was before, and the other seems more useful.

**Comment by kingthorin** [comment]
But not both projects were for passive scanning. 2018 was more scanning infra and 2019 was actually the scanning and scripts/rules.

**Comment by kingthorin** [comment]
Make sense?

**Comment by thc202** [comment]
I'd still prefer how it was, but fine to go as is.

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
> I'd still prefer how it was, but fine to go as is.

So you'd rather they were both the 2019 link?

**Review by psiinon — APPROVED** [review]

**Comment by thc202** [comment]
That's how it was, but as said, fine as is.

**Pull request merged**
